Feature branch
newhorizon-tech/custom_enumerables pull request #2
Opened 2020-10-13 15:57 UTC by newhorizon-tech

Created custom Ruby enumerables:

- my_each
- my_select
- my_all?
- my_inject
- my_map 

and others

2020-10-13 18:01 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for the well done job
However, there are some issues that need to be solved.

Kindly read the comments left below to know more about them
Fix them and submit a new code review request

Thanks

Mael FOSSO

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :014 > block = proc { |num| num < 4 }
2.6.5 :015 > array.my_each(&block)
 => 100 
2.6.5 :016 > array.each(&block)
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :017 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :019 > range = Range.new(5, 50)
2.6.5 :020 > range.my_each(&block)
 => 46 
2.6.5 :021 > range.each(&block)
 => 5..50 
2.6.5 :022 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :024 > block = proc { |num| num < 4 }
2.6.5 :025 > array.my_each_with_index(&block)
 => 100 
2.6.5 :026 > array.each_with_index(&block)
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :027 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :029 > range = Range.new(5, 50)
2.6.5 :030 > range.my_each_with_index(&block)
 => 46 
2.6.5 :031 > range.each_with_index(&block)
 => 5..50 
2.6.5 :032 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :040 > block = proc { |num| num < 4 }
2.6.5 :041 > range = Range.new(5, 50)
2.6.5 :042 > range.my_select(&block)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):42
        1: from enum.rb:23:in `my_select'
NameError (undefined local variable or method `length' for 5..50:Range)
2.6.5 :043 > range.select(&block)
 => [] 
2.6.5 :044 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :046 > false_block = proc { |num| num > 9 }
2.6.5 :047 > range = Range.new(5, 50)
2.6.5 :048 > range.my_all?(&false_block)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):48
        1: from enum.rb:35:in `my_all?'
NameError (undefined local variable or method `length' for 5..50:Range)
2.6.5 :049 > range.all?(&false_block)
 => false 
2.6.5 :050 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :057 > false_array = [1, false, 'hi', []]
2.6.5 :058 > false_array.my_all?
 => true 
2.6.5 :059 > false_array.all?
 => false 
2.6.5 :060 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :062 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :063 > array_clone = array.dup
2.6.5 :064 > array_clone[0] = 'word'
2.6.5 :065 > array_clone.all?(Integer)
 => false 
2.6.5 :066 > array_clone.my_all?(Integer)
 => true 
2.6.5 :067 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :069 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :070 > words.my_all?(/o/)
 => true 
2.6.5 :071 > words.all?(/o/)
 => false 
2.6.5 :072 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :074 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :075 > array.my_all?(3)
 => true 
2.6.5 :076 > array.all?(3)
 => false 
2.6.5 :077 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :079 > false_block = proc { |num| num > 9 }
2.6.5 :080 > range.my_any?(&false_block)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):80
        1: from enum.rb:45:in `my_any?'
NameError (undefined local variable or method `length' for 5..50:Range)
2.6.5 :081 > range.any?(&false_block)
 => true 
2.6.5 :082 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :084 > true_array = [nil, false, true, []]
2.6.5 :085 > true_array.my_any?
 => false 
2.6.5 :086 > true_array.any?
 => true 
2.6.5 :087 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :089 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :090 > array.my_any?(Numeric)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):90
        1: from enum.rb:42:in `my_any?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :092 > array.any?(Numeric)
 => true 
2.6.5 :093 >
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :096 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :097 > words.my_any?(Integer)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):97
        1: from enum.rb:42:in `my_any?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :098 > words.any?(Integer)
 => false 
2.6.5 :099 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :101 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :102 > words.my_any?(/z/)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):102
        1: from enum.rb:42:in `my_any?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :103 > words.any?(/z/)
 => false 
2.6.5 :104 > words.my_any?(/d/))
Traceback (most recent call last):
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        2: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        1: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
SyntaxError ((irb):104: syntax error, unexpected ')', expecting end-of-input)
words.my_any?(/d/))
                  ^
2.6.5 :105 > words.my_any?(/d/)
Traceback (most recent call last):
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        3: from (irb):104
        2: from (irb):105:in `rescue in irb_binding'
        1: from enum.rb:42:in `my_any?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :106 > words.any?(/d/)
 => true 
2.6.5 :107 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :109 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :110 > words.my_any?('cat')
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):110
        1: from enum.rb:42:in `my_any?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :111 > words.any?('cat')
 => false 
2.6.5 :112 > words_clone = words.dup
2.6.5 :113 > words_clone[0] = 'cat'
2.6.5 :114 > words_clone.any?('cat')
 => true 
2.6.5 :115 > words_clone.my_any?('cat')
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):115
        1: from enum.rb:42:in `my_any?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :116 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :120 > range = Range.new(5, 50)
2.6.5 :121 > false_block = proc { |num| num > 9 }
2.6.5 :122 > range.my_none?(&false_block)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):122
        1: from enum.rb:57:in `my_none?'
NameError (undefined local variable or method `length' for 5..50:Range)
2.6.5 :123 > range.none?(&false_block)
 => false 
2.6.5 :124 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :126 > true_array = [nil, false, true, []]
2.6.5 :127 > true_array.my_none?
 => true 
2.6.5 :128 > true_array.none?
 => false 
2.6.5 :129 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :131 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :132 > array.none?(String)
 => true 
2.6.5 :133 > array.my_none?(String)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):133
        1: from enum.rb:54:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :134 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :136 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :137 > array.my_none?(Numeric)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):137
        1: from enum.rb:54:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :138 > array.none?(Numeric)
 => false 
2.6.5 :139 > array_clone = array.dup
2.6.5 :140'> array_clone[0] = 'hi
2.6.5 :141 > '
2.6.5 :142 > array_clone
 => ["hi\n", 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :143 > array_clone.my_none?(String)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):143
        1: from enum.rb:54:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :144 > array_clone.none?(String)
 => false 
2.6.5 :145 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :147 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :148 > words.none?(/z/)
 => true 
2.6.5 :149 > words.none?(/d/)
 => false 
2.6.5 :150 > words.my_none?(/z/)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):150
        1: from enum.rb:54:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :151 > words.my_none?(/d/)
Traceback (most recent call last):
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        3: from (irb):150
        2: from (irb):151:in `rescue in irb_binding'
        1: from enum.rb:54:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :152 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :154 > range = Range.new(5, 50)
2.6.5 :155 > range.count
 => 46 
2.6.5 :156 > range.my_count
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):156
        1: from enum.rb:79:in `my_count'
NameError (undefined local variable or method `length' for 5..50:Range)
2.6.5 :157 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :159 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :160 > array.map.is_a?(Enumerator)
 => true 
2.6.5 :161 > array.my_map.is_a?(Enumerator)
Traceback (most recent call last):
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        4: from (irb):161
        3: from enum.rb:86:in `my_map'
        2: from enum.rb:86:in `times'
        1: from enum.rb:87:in `block in my_map'
LocalJumpError (no block given (yield))
2.6.5 :162 > 
```
Must returns an enumerator

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +  end
```rb
2.6.5 :164 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :165 > my_proc = proc { |num| num > 10 }
2.6.5 :166 > array.my_map(my_proc) { |num| num < 10 }
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):166
        1: from enum.rb:83:in `my_map'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :167 > array.map(&my_proc)
 => [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] 
2.6.5 :168 > 
```
It must execute only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +end
```rb
2.6.5 :171 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :172 > array.my_inject(:+)
Traceback (most recent call last):
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        4: from (irb):172
        3: from enum.rb:100:in `my_inject'
        2: from enum.rb:100:in `times'
        1: from enum.rb:102:in `block in my_inject'
LocalJumpError (no block given (yield))
2.6.5 :173 > array.inject(:+)
 => 421 
2.6.5 :174 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +end
```rb
2.6.5 :176 > range = Range.new(5, 50)
2.6.5 :177 > range.my_inject(:*)
Traceback (most recent call last):
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        4: from (irb):177
        3: from enum.rb:100:in `my_inject'
        2: from enum.rb:100:in `times'
        1: from enum.rb:102:in `block in my_inject'
LocalJumpError (no block given (yield))
2.6.5 :178 > range.inject(:*)
 => 1267253883404724085150525340252698701849068398706688000000000000 
2.6.5 :179 > 

```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +end
```rb
2.6.5 :181 > array
 => [1, 3, 4, 4, 3, 2, 6, 8, 6, 8, 5, 4, 1, 2, 6, 4, 5, 0, 8, 4, 8, 6, 1, 4, 3, 7, 1, 1, 3, 4, 3, 2, 8, 0, 0, 6, 6, 8, 8, 3, 0, 6, 0, 5, 8, 2, 2, 4, 7, 6, 3, 2, 6, 1, 8, 8, 6, 7, 7, 0, 2, 6, 4, 1, 6, 0, 5, 6, 4, 7, 1, 7, 6, 5, 2, 6, 7, 8, 2, 0, 3, 7, 0, 1, 6, 4, 4, 5, 6, 3, 7, 3, 0, 2, 7, 5, 2, 5, 7, 5] 
2.6.5 :182 > array.my_inject(20, :*)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):182
        1: from enum.rb:92:in `my_inject'
ArgumentError (wrong number of arguments (given 2, expected 0..1))
2.6.5 :183 > array.inject(20, :*)
 => 0 
2.6.5 :184 > 
```

2020-10-13 18:01 UTC, maelfosso commented on enum.rb
> +end
```rb
2.6.5 :186 > range.my_inject(2, :*)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):184
        1: from enum.rb:92:in `my_inject'
ArgumentError (wrong number of arguments (given 2, expected 0..1))
2.6.5 :187 > range.inject(2, :*)
 => 2534507766809448170301050680505397403698136797413376000000000000 
2.6.5 :188 > 
```

2020-10-14 15:49 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @newhorizon-tech  and @tahiry-dev  . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] ```my_inject``` is not passing all test cases. The inject method is not passing the assigned value to the block when it's given. Example:
```
[1, 2, 3].inject(4) { |sum, n| sum + n }    # 10
[1, 2, 3].my_inject(4) { |sum, n| sum + n } # 6
```
The issue is that ```sum``` in the ```my_each``` is starting with a value of ```0``` instead of taking into consideration the passed value of ```4```.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-14 21:29 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

#### Hi, @newhorizon-tech and @tahiry-dev  

Congratulations! You've both done well on fixing the 'my_inject' method requested by the previous TSE. 
Your solutions are now passing all test cases 

Update your PR title to a meaningful one and feel free to merge when you are ready. 
All the best on your next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-15 06:46 UTC, merged